name: Pycodestyle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install -r requirements.txt
    - name: Analysing the code with pycodestyle
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD/libs
        pycodestyle --max-line-length=120 .
